/* AUTOGENERATED FILE - DO NOT EDIT CONTENTS */

export const projectId = "pcbhdbxpmntdmpfiffyr"
export const publicAnonKey = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBjYmhkYnhwbW50ZG1wZmlmZnlyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjM0NDM4MDcsImV4cCI6MjA3OTAxOTgwN30.wgyzXSW65HEXwgeey_e3Zhe6cb-NXbMA_Hyy-DmGoZM"